name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      new_tag_version: ${{ steps.create_release.outputs.new_release_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build the project
        run: npm run build

      - name: Dry Run
        id: tag_version
        run: |
          export NEW_TAG_VERSION=$(npx semantic-release --dry-run | grep "The next release version is" | awk '{print $6}')
          echo "new_tag_version=$NEW_TAG_VERSION" >> $GITHUB_ENV
      
      - name: Generate Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release